-- AlterTable
ALTER TABLE `Order` ADD COLUMN `paymentMethod` VARCHAR(191) NULL,
    ADD COLUMN `paymentOrderId` VARCHAR(191) NULL,
    ADD COLUMN `paymentStatus` VARCHAR(191) NULL,
    MODIFY `status` ENUM('PENDING_PAYMENT', 'PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'PENDING_PAYMENT';
