-- AlterTable
ALTER TABLE `Order` MODIFY `status` ENUM('PENDING_PAYMENT', 'PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', 'REFUND_PROCESSING') NOT NULL DEFAULT 'PENDING_PAYMENT';
